from typing import Protocol


class CameraAdapter(Protocol):
    def probe(self) -> dict: ...
    def get_capabilities(self) -> dict: ...
    def get_current_settings(self) -> dict: ...
    def apply_settings(self, values: dict) -> None: ...
