"""enforce tenant references

Revision ID: 0003
Revises: 0002
"""

from alembic import op

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade():
    op.create_unique_constraint("uq_users_id_tenant", "users", ["id", "tenant_id"])
    op.create_check_constraint(
        "ck_role_scope",
        "user_roles",
        "(role_name = 'SUPER_ADMIN' AND tenant_id IS NULL) OR (role_name <> 'SUPER_ADMIN' AND tenant_id IS NOT NULL)",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_capability_camera_tenant",
        "camera_capabilities",
        "cameras",
        ["camera_id", "tenant_id"],
        ["id", "tenant_id"],
    )
    op.create_foreign_key(
        "fk_setting_camera_tenant",
        "camera_settings",
        "cameras",
        ["camera_id", "tenant_id"],
        ["id", "tenant_id"],
    )
    op.create_foreign_key(
        "fk_command_camera_tenant",
        "device_commands",
        "cameras",
        ["camera_id", "tenant_id"],
        ["id", "tenant_id"],
    )
    op.create_foreign_key(
        "fk_permission_user_tenant",
        "user_camera_permissions",
        "users",
        ["user_id", "tenant_id"],
        ["id", "tenant_id"],
    )
    op.create_foreign_key(
        "fk_permission_camera_tenant",
        "user_camera_permissions",
        "cameras",
        ["camera_id", "tenant_id"],
        ["id", "tenant_id"],
    )
    op.create_foreign_key(
        "fk_role_user_tenant", "user_roles", "users", ["user_id", "tenant_id"], ["id", "tenant_id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_role_scope", "user_roles", type_="check")
    op.drop_constraint("fk_role_user_tenant", "user_roles", type_="foreignkey")
    op.drop_constraint("fk_permission_camera_tenant", "user_camera_permissions", type_="foreignkey")
    op.drop_constraint("fk_permission_user_tenant", "user_camera_permissions", type_="foreignkey")
    op.drop_constraint("fk_command_camera_tenant", "device_commands", type_="foreignkey")
    op.drop_constraint("fk_setting_camera_tenant", "camera_settings", type_="foreignkey")
    op.drop_constraint("fk_capability_camera_tenant", "camera_capabilities", type_="foreignkey")
    op.drop_constraint("uq_users_id_tenant", "users", type_="unique")
    # ### end Alembic commands ###
